' Copyright (c) 2022 Thomas Hugo Williams
' License MIT <https://opensource.org/licenses/MIT>
' For MMBasic 5.07.05

Const keycode.BACKSPACE    = &h08
Const keycode.TAB          = &h09
Const keycode.ENTER        = &h0A
Const keycode.ESCAPE       = &h1B
Const keycode.SPACE        = &h20
Const keycode.DELETE       = &h7F
Const keycode.UP           = &h80
Const keycode.DOWN         = &h81
Const keycode.LEFT         = &h82
Const keycode.RIGHT        = &h83
Const keycode.INSERT       = &h84
Const keycode.HOME         = &h86
Const keycode.END          = &h87
Const keycode.PAGE_UP      = &h88
Const keycode.PAGE_DOWN    = &h89
Const keycode.ALT          = &h8B
Const keycode.F1           = &h91
Const keycode.F2           = &h92
Const keycode.F3           = &h93
Const keycode.F4           = &h94
Const keycode.F5           = &h95
Const keycode.F6           = &h96
Const keycode.F7           = &h97
Const keycode.F8           = &h98
Const keycode.F9           = &h99
Const keycode.F10          = &h9A
Const keycode.F11          = &h9B
Const keycode.F12          = &h9C
Const keycode.PRINT_SCREEN = &h9D

keycode.string_data:
Data "", "", "", "", "", "", "", ""
Data "Backspace", "Tab", "Enter", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "Escape", "", "", "", ""
Data "Space", "!", "", "#", "$", "%", "&", "'"
Data "(", ")", "*", "+", ",", "-", ".", "/"
Data "0", "1", "2", "3", "4", "5", "6", "7"
Data "8", "9", ":", ";", "<", "=", ">", "?"
Data "@", "A", "B", "C", "D", "E", "F", "G"
Data "H", "I", "J", "K", "L", "M", "N", "O"
Data "P", "Q", "R", "S", "T", "U", "V", "W"
Data "X", "Y", "Z", "[", "\", "]", "^", "_"
Data "`", "a", "b", "c", "d", "e", "f", "g"
Data "h", "i", "j", "k", "l", "m", "n", "o"
Data "p", "q", "r", "s", "t", "u", "v", "w"
Data "x", "y", "z", "{", "|", "}", "~", "Delete"
Data "Up", "Down", "Left", "Right", "Insert", "", "Home", "End"
Data "Page Up", "Page Down", "", "Alt", "", "", "", ""
Data "", "F1", "F2", "F3", "F4", "F5", "F6", "F7"
Data "F8", "F9", "F10", "F11", "F12", "Prt Scr", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
Data "", "", "", "", "", "", "", ""
